[package]
name = "ytpodcast"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Lorenzo Carbonell <lorenzo.carbonell.cerezo@gmail.com>"]
rust-version = "1.64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5", features = ["runtime-actix-rustls", "sqlite", "macros", "offline", "chrono"]}
actix-web = "4"
actix-http = "3.2"
actix-service = "2"
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.9"
reqwest = "0.11"
async-recursion = "1.0"
actix-rt = "2.7"
rss = "2.0"
tokio = { vesrion = "1.21", features = ["full"]}
