[package]
name = "ytpodcast"
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["Lorenzo Carbonell <lorenzo.carbonell.cerezo@gmail.com>"]
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core dependencies: runtime, HTTP framework and database client.
tokio = { version = "1.22", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.6" }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "sqlite", "macros", "offline", "chrono"]}

# State of the art password hashing
argon2 = "0.4"

# Axum builds on the types in Tower
tower = "0.4"
tower-http = { version = "0.3.0", features = [ "trace" ] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Utility
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1"
dotenv = "0.15"
rand = "0.8"
thiserror = "1.0"
chrono = "0.4"
