[package]
name = "ytpodcast"
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["Lorenzo Carbonell <lorenzo.carbonell.cerezo@gmail.com>"]
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core dependencies: runtime, HTTP framework and database client.
tokio = { version = "1.22", features = ["full", "time"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "sqlite", "macros", "offline", "chrono"] }
axum = { version = "0.6" , features = ["multipart"] }
openssl = { version = "0.10", features = ["vendored"] }

# Axum builds on the types in Tower
tower = "0.4"
tower-http = { version = "0.3.5", features = [ "trace", "fs" ] }

# Templates
tera = "1.17"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Utility
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
regex = "1"
base64 = "0.20"

# RSS
rss = "2.0"
