production: true
title: u2vpodcast
url: localhost
port: 6996
sleep_time: 1
per_page: 10
jwt_secret: "pxWGSDw8pie2TPZcqfFdpBgxwzp08fz4UTJ2q8pSfP80Df74PE8HcrjXV3hsOyZTgCpBvXtmn2O7qqtXigJM0Q=="
jwt_expires_in: 1m
jwt_maxage: 3600
secret_key: "pxWGSDw8pie2TPZcqfFdpBgxwzp08fz4UTJ2q8pSfP80Df74PE8HcrjXV3hsOyZTgCpBvXtmn2O7qqtXigJM0Q=="
