log_level: info
db_url: sqlite:ytpodcast.db
port: 8080
sleep_time: 1
with_authentication: false
username: username
password: password
url: http://ytpodcast.enriquemorales.ml
cookies: cookies.txt
channels:
  - url: https://www.youtube.com/@linuxytapas2840/videos
    title: Linux y Tapas
    description: Linux y Tapas
    image: https://yt3.googleusercontent.com/Q5_FzQWmSRc1d1gn0pFOcF7jhSwLZfwZt8zVTCe7eVsQRWO0PJazaRZF1mRGd-QMKWW3_HZPcg
