log_level: info
db_url: sqlite:ytpodcast.db
port: 8080
sleep_time: 1
username: username
password: password
title: title
description: description
url: http://localhost:8080
cookies: cookies.txt
folder: /tmp
hmac_key: mak
ytdlp_path: /usr/bin/yt-dlp
