services:
  u2vpodcast:
    image: atareao/u2vpodcast:latest
    container_name: u2vpodcast
    init: true
    restart: always
    environment:
      RUST_ENV: production
    volumes:
      - audios:/app/audios
      - db:/app/db
      - ./cookies.txt:/app/cookies.txt
    ports:
      - 6996:6996

volumes:
  audios: {}
  db: {}
