version: "3.7"

services:
  u2vpodcast:
    image: atareao/u2vpodcast:latest
    container_name: u2vpodcast
    init: true
    restart: always
    volumes:
      - audios:/app/audios
      - db:/app/db
      - ./cookies.txt:/app/cookies.txt:ro
      - ./config.yml:/app/config.yml:ro
    networks:
      - proxy

volumes:
  audios: {}
  db: {}

networks:
  proxy:
    external: true

