# GENERAL

GET http://localhost:{{PORT}}

# CHANNELS

GET http://localhost:{{PORT}}/api/v1/channels

GET http://localhost:{{PORT}}/channels/7

POST http://localhost:{{PORT}}/channels
Content-Type: application/json

{
    "yt_id": "UCcBPQRPSQc1z_FCnc74I2Pw",
    "title": "Linux y Tapas",
    "last": "1979-08-22T10:20:00Z"
}


DELETE http://localhost:{{PORT}}/channels/1

# EPISODES

GET http://localhost:{{PORT}}/api/v1/episodes

GET http://localhost:{{PORT}}/episodes/2

POST http://localhost:{{PORT}}/episodes
Content-Type: application/json

{
    "channel_id": 2,
    "title": "título",
    "description": "description",
    "yt_id": "1234",
    "link": "https://atareao.es",
    "published_at": "2022-08-22T10:20:00.000Z",
    "image": "https://atareao.es/image",
    "listen": false
}


DELETE http://localhost:{{PORT}}/episodes/1

# FEED

GET http://localhost:{{PORT}}/rss

POST http://localhsot:{{PORT}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "atareao@atareao.es",
    "password": "12345678"
}
